- src/components/books/BookEditCoverModal.vue
- src/directives/index.js
- src/main.js
- static/bookcovers.json
- To be able to move the position of the text
- Make bookcover selectable
It needs still development.
> Client: Book cover editor

- src/components/users/UserAddModal.vue
Pulling in changes from David on user Crud
> Feature add user crud

- src/components/books/BookMetaEdit.vue
- src/components/books/BooksGrid.vue
- src/components/login.vue
- src/store/index.js
Fixed basic functionality with metadata
> Feature syncbooks

- package.json
- src/App.vue
- src/components/books/BookEditCoverModal.vue
- src/components/books/BookImport.vue
- src/components/books/BookMetaEdit.vue
- src/components/login.vue
- src/store/index.js
- static/bookcovers.json
Added tabbed interface to cover editor to allow uploading cover until such time as we can get html2canvas based editor working
> Feature covereditor

- src/components/books/BlockView.vue
- src/components/books/BookEdit.vue
- src/components/books/BookEditToolbar.vue
- src/components/books/BooksGrid.vue
- src/components/books/BooksToolbar.vue
- src/components/login.vue
- src/mixins/access.js
- src/store/index.js
Integration of working features surrounding block editing
> Feature editor

- src/components/audio/AudioImport.vue
Got working audio upload on client. No narrator name yet
> updated audio import popup

- src/components/MainMenu.vue
- src/components/Users.vue
- src/components/login.vue
- src/components/users/UserAddModal.vue
- src/components/users/WorkHistoryModal.vue
- src/filters/index.js
- static/roles.json
- static/users.json
> Dev users crud

- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
- src/components/books/audTest/audTest.vue
- src/components/generic/BlockContextMenu.vue
- src/components/generic/BlockMenu.vue
- src/store/index.js
Footnotes, Undo all unsaved changes.
> Ilm 61 update wysiwyg

- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
ILM-202 Save changes in blocks before join
> Ilm new tasks flow

- src/components/books/BookBlockView.vue
- src/components/generic/BlockFlagPopup.vue
> Ilm custom scroll

- package.json
- src/components/Books.vue
- src/components/books/BookEditToolbar.vue
- src/components/books/BookMetaEdit.vue
- src/store/index.js
origin/ILM-654
ILM-654 Generate Demo book
ILM-1371 Generate demo book. Export. The Narrator and Proofer are able to use the buttons from the Export section of the Book Meta. 
ILM-1365 Export. The previously published book have active buttons <Mp3 Zip>, <Flac Zip>, but pressing them does not lead to the downloading zip files
ILM-1401 Generate Demo book. The building of the Dawn Breakers book does not happen
ILM-1363 Export. The time of the build displayed in the Export section does not match with the time of a user.
ILM-1362 Export. Visualization of the Export section does not match requirements
ILM-1357 Export. Meta. The button <Copy Demo Link> does not provide the link which leads to the demo book
ILM-1356 META. The button <Export Audio> is present on the Audio Integration panel.
> Ilm release 190129

- src/components/AudioEditor.vue
- src/components/Books.vue
- src/components/Tasks.vue
- src/components/audio/AudioImport.vue
- src/components/books/BookAudioIntegration.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
- src/components/books/BookEditToolbar.vue
- src/components/books/BookEdit_Display.vue
- src/components/books/BookMetaEdit.vue
- src/components/books/BookReimport.vue
- src/components/books/BooksGrid.vue
- src/components/books/BooksToolbar.vue
- src/components/books/css/ilm_base.less
- src/components/books/details/BookAssignments.vue
- src/components/books/details/BookWorkflow.vue
- src/components/collections/CollectionsGrid.vue
- src/components/collections/CollectionsToolbar.vue
- src/components/collections/LinkBook.vue
- src/components/generic/Grid.vue
- src/components/tasks/TaskAddModal.vue
- src/mixins/task_controls.js
- src/router/index.js
- src/store/bookBlock.js
- src/store/bookBlocks.js
- src/store/index.js
- src/store/liveDB.js
origin/ILM-1247
(T) ILM-1247 Make block player waveform visible
(T) ILM-1248 Move Start/End positions along with word boundaries
(B) ILM-1566 Block Audio Player. if a user selects a word from the block to display it in the block audio player and move the borders of the words, the borders of the audio is not changing its position
(B) ILM-1567 Block Audio Player. Wrong highlighted word in the block audio player
(B) ILM-1570 Block Audio Player. Adding a text to the block with open block audio player leads to an error in the console: Cannot read property 'getEventEmitter' of null
origin/ILM-231
(S) ILM-231 Archive book
(B) ILM-1637 Archive book. The font of the archived book in the collection is not grey
(B) ILM-1642 Archive Book. Import audio by a Power user in the archived book, does not …
> Ilm release 190327

- .gitignore
- src/components/AudioEditor.vue
- src/components/Books.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
- src/components/books/BookEditToolbar.vue
- src/components/books/BookImport.vue
- src/components/books/BookMetaEdit.vue
- src/components/books/BooksGrid.vue
- src/components/books/BooksToolbar.vue
- src/components/books/css/ilm_base.less
- src/components/books/details/BookAssignments.vue
- src/components/books/details/BookPublish.vue
- src/components/books/details/BookWorkflow.vue
- src/components/collections/CollectionsGrid.vue
- src/components/collections/CollectionsToolbar.vue
- src/components/generic/ExtMediumEditor.js
- src/mixins/task_controls.js
- src/store/bookBlocks.js
- src/store/index.js
- src/store/liveDB.js
origin/ILM-533
(S) ILM-533 Book status on book listing
(B) ILM-497 Books List. There is duplicated functionality
(B) ILM-1780 Book status. The status "Book import" is not displayed 
(B) ILM-1790 Editor. The book with STATUS completed. The tabs <Audio> and <Styles> are not displayed for editor in opened book
(B) ILM-1805 Completed book status. Editor. Editor can not edit metadata in the book that has status "Completed"
origin/ILM-1322
(S) ILM-1322 Change voicework on unpublished Book
(B) ILM-1718 Change voicework on unpublished Book. Mastering phase. If user selects "No audio" voicework he is not able to complete task
(B) ILM-1496 Book content updates by Editor in unpublished book
(B) ILM-1791 The button <Approve> is displayed for the block where footnotes have voicework TTS but were not …
> Release 2019_04_24

- src/components/Books.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
- src/components/books/css/ilm_base.less
- src/components/generic/ButtonRadioGroup.vue
Reverts chadananda/ilm-client#467
> Revert "ILM-2358 implemented"

- src/components/books/BookBlockPartPreview.vue
- src/components/books/BookBlockPartView.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
Reverts chadananda/ilm-client#482
> Revert "extractor adjusted bottom controls part 2"

- src/components/books/BookBlockPartPreview.vue
- src/components/books/BookBlockPartView.vue
Reverts chadananda/ilm-client#480
> Revert "extractor adjusted bottom controls"

- src/components/books/BookBlockPartView.vue
This reverts commit 7a17cf0124096491428456ba01efa0a40a906167.
> Revert "<bug>(ILM-2992)"

- src/components/AudioEditor.vue
- src/components/books/BookBlockView.vue
> Release_2021_07_01_hotfix

- package.json
- src/components/AudioEditor.vue
- src/components/books/BookAudioIntegration.vue
- src/components/books/BookBlockPartView.vue
- src/components/books/BookBlockView.vue
- src/store/audio/AudioTimeScale.js
- src/store/audio/AudioTrackRender.js
- src/store/bookBlock.js
- src/store/index.js
Tasks:
ILM-4200 - ""In Audio Editor: keep scroll, selected range and play position steady at Save&Realign""
ILM-2828 - "Split block"
ILM-4020 - "Word ID reserve distribution at block split"
ILM-4198 - "Update audio file name. Enlarge editing field"
Issues:
ILM- 4153 - "Title. Block subtype. The subtype is not displayed in the block attributes after splitting block or changing voicework" 
ILM-4155 - "Block number. Hardcode block number. Header. The inserted block does not receive correct block number" 
ILM-4192 -  "Audio editor. The audio editor hangs up after setting pinned position in several blocks one by one" 
ILM-4033  - "Original player /Audio editor The block player audio track is displayed black for the new Chrome version 91.0.4472.77"
ILM-4249 - "Audio editor. The big block . The …
> Release_2021_08_19

- src/components/AudioEditor.vue
- src/components/books/BookBlockPartView.vue
- src/components/books/BookBlockView.vue
- src/components/books/details/CompleteAudioExport.vue
- src/store/bookBlock.js
- src/store/index.js
Tasks:
ILM-4199 - Export selected block range to MD and m4a (Scope 1)
ILM-4267 - Insert accurate "pause before" in joined m4a
ILM-4260 - Default "0" pause before Narration blocks
Issues:
ILM-4188 - Audio Editor. To trigger discard changes pop-up message user has to press twice the audio editor button of next block
> Release_2021_09_03

- src/App.vue
- src/components/AudioEditor.vue
- src/components/Books.vue
- src/components/Collections.vue
- src/components/books/BookBlockPartView.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookEdit.vue
Move AudioEditor container on upper level. Discard fixed position.
> 0.155 ilm 5087 audio editor layout

- src/components/books/BookEdit.vue
Add search to collection proofread mode
> HotFix_0.156_2022_10_25

- src/components/books/details/CompleteAudioExport.vue
> Revert "0.158 06.12.2022 lisu ilm 5426"

- src/components/books/BookEdit.vue
> <improvement>(ILM-3183):apply new properties to cancel button at join blocks confirm window

- src/components/MainMenu.vue
- src/store/index.js
Welcome message should contain Username if Real Name is absent
> 0.159_04.01.2023_pere_ilm-3196

- src/components/Users.vue
- src/components/generic/SelectRoles.vue
- src/components/tasks/TaskAddModal.vue
- static/roles.json
> 0.158_30.12.2022_pere ilm 5432

- src/components/collections/CollectionCoverModal.vue
fixed 'save' in collections 
for task ILM-5534
> 0.159_12.01.2023_pere_ILM-5504 

- src/components/books/BookEditCoverModal.vue
- src/components/collections/CollectionCoverModal.vue
> 0.159_26.01.2023_pere_ILM-5504

- src/components/MainMenu.vue
fix bag with {} in welcome message
> 0.159_04.01.2023_pere_ILM_31962

- src/components/Tasks.vue
- src/components/books/BookAudioIntegration.vue
- src/components/books/details/BookAssignments.vue
- src/components/books/details/ReplaceAudio.vue
(cherry picked from commit ba3e344e1936f7f3770a68381fcf9d278eacd3eb)
> <story>(ILM-5557): do not close on click

- src/components/AudioEditor.vue
- src/components/audio/AudioImport.vue
- src/components/books/BookBlockView.vue
- src/components/books/BookMetaEdit.vue
- src/components/books/details/ElevenLabsTTS.vue
- src/components/books/details/PauseAfterBlock.vue
- src/components/collections/CollectionMeta.vue
- src/components/toolbar/AllListsToolbar.vue
- src/store/index.js
Merging defects from sprint 164:
ILM-5173 “Flag. Narration mode. Narrator can set the flag for the block with Audio voicework/TTS/No audio”
ILM-6101 “Pause before the block. The pause area (slider and field for writing pause) is not disabled when the range of blocks is marked”
ILM-5666 “Import audio file into the audio catalog. The import audio process hangs up”
ILM-6096 “Redactor pop-up. Illustration/Footnote. The styles from redactor pop-up are not set from the first time in illustration/footnote description when the changes are unsaved.”
ILM-6195 “Eleven Labs TTS. The TTS audio catalog is twitched after adding a new voice”
ILM-6199 “Book/Collection listing. Filter. The data disappears in the filter field”
ILM-6202 “Pause after block. The space between the text and the slider is not …
> 0.164 defects

- src/components/books/BooksGrid.vue
- src/components/collections/CollectionGrid.vue
Collection.Power users. The sorting by Book columns Title/Author/Published/Updated/Status/State does not work in Collection
> Add sort & fix editors

- src/components/books/BookBlockPartView.vue
- src/components/generic/medium-editor/js/medium-editor.js
Hot fix defect
ILM-6549 "Pilcrow. The pilcrow appears in the place where it should not be"
> Release_2024_03_11_HF

- src/components/books/BookBlockView.vue
- src/components/books/block/RecordingBlock.vue
Fix styles & appearance behavior.
> fix-narration-popup-record-label

- src/components/toolbar/AllListsToolbar.vue
> Revert "Check log"

- src/components/toolbar/AllListsToolbar.vue
> Revert "Revert "Check log""

- src/components/tasks/TaskAddModal.vue
- src/components/toolbar/AllListsToolbar.vue
> Revert "Check logs"

- src/components/Books.vue
- src/components/Tasks.vue
- src/components/books/BookEdit.vue
- src/components/tasks/TaskAddModal.vue
- src/components/toolbar/AllListsToolbar.vue
- src/store/modules/tasks.js
> Revert "Refactor Task Add Modal"

- src/components/toolbar/AllListsToolbar.vue
> Revert "Revert "Revert "Check log"""
